// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Rixl.Sdk.Models.Billing.V1
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CalculateTaxRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The amount property</summary>
        public double? Amount { get; set; }
        /// <summary>The billingAddress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Rixl.Sdk.Models.Billing.V1.BillingAddress? BillingAddress { get; set; }
#nullable restore
#else
        public global::Rixl.Sdk.Models.Billing.V1.BillingAddress BillingAddress { get; set; }
#endif
        /// <summary>The billingCycle property</summary>
        public global::Rixl.Sdk.Models.Billing.V1.BillingCycle? BillingCycle { get; set; }
        /// <summary>The currency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>The intervalCount property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? IntervalCount { get; set; }
#nullable restore
#else
        public UntypedNode IntervalCount { get; set; }
#endif
        /// <summary>The lineItems property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Rixl.Sdk.Models.Billing.V1.TaxLineItem>? LineItems { get; set; }
#nullable restore
#else
        public List<global::Rixl.Sdk.Models.Billing.V1.TaxLineItem> LineItems { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Rixl.Sdk.Models.Billing.V1.CalculateTaxRequest_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Rixl.Sdk.Models.Billing.V1.CalculateTaxRequest_metadata Metadata { get; set; }
#endif
        /// <summary>The orgId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrgId { get; set; }
#nullable restore
#else
        public string OrgId { get; set; }
#endif
        /// <summary>The planId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlanId { get; set; }
#nullable restore
#else
        public string PlanId { get; set; }
#endif
        /// <summary>The planName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlanName { get; set; }
#nullable restore
#else
        public string PlanName { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Models.Billing.V1.CalculateTaxRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Rixl.Sdk.Models.Billing.V1.CalculateTaxRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Rixl.Sdk.Models.Billing.V1.CalculateTaxRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetDoubleValue(); } },
                { "billingAddress", n => { BillingAddress = n.GetObjectValue<global::Rixl.Sdk.Models.Billing.V1.BillingAddress>(global::Rixl.Sdk.Models.Billing.V1.BillingAddress.CreateFromDiscriminatorValue); } },
                { "billingCycle", n => { BillingCycle = n.GetEnumValue<global::Rixl.Sdk.Models.Billing.V1.BillingCycle>(); } },
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "intervalCount", n => { IntervalCount = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "lineItems", n => { LineItems = n.GetCollectionOfObjectValues<global::Rixl.Sdk.Models.Billing.V1.TaxLineItem>(global::Rixl.Sdk.Models.Billing.V1.TaxLineItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Rixl.Sdk.Models.Billing.V1.CalculateTaxRequest_metadata>(global::Rixl.Sdk.Models.Billing.V1.CalculateTaxRequest_metadata.CreateFromDiscriminatorValue); } },
                { "orgId", n => { OrgId = n.GetStringValue(); } },
                { "planId", n => { PlanId = n.GetStringValue(); } },
                { "planName", n => { PlanName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("amount", Amount);
            writer.WriteObjectValue<global::Rixl.Sdk.Models.Billing.V1.BillingAddress>("billingAddress", BillingAddress);
            writer.WriteEnumValue<global::Rixl.Sdk.Models.Billing.V1.BillingCycle>("billingCycle", BillingCycle);
            writer.WriteStringValue("currency", Currency);
            writer.WriteObjectValue<UntypedNode>("intervalCount", IntervalCount);
            writer.WriteCollectionOfObjectValues<global::Rixl.Sdk.Models.Billing.V1.TaxLineItem>("lineItems", LineItems);
            writer.WriteObjectValue<global::Rixl.Sdk.Models.Billing.V1.CalculateTaxRequest_metadata>("metadata", Metadata);
            writer.WriteStringValue("orgId", OrgId);
            writer.WriteStringValue("planId", PlanId);
            writer.WriteStringValue("planName", PlanName);
        }
    }
}
#pragma warning restore CS0618
