// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Rixl.Sdk.Models.Billing.V1
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SubscriptionStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "SUBSCRIPTION_STATUS_UNSPECIFIED")]
        #pragma warning disable CS1591
        SUBSCRIPTION_STATUS_UNSPECIFIED,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUBSCRIPTION_STATUS_ACTIVE")]
        #pragma warning disable CS1591
        SUBSCRIPTION_STATUS_ACTIVE,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUBSCRIPTION_STATUS_INACTIVE")]
        #pragma warning disable CS1591
        SUBSCRIPTION_STATUS_INACTIVE,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUBSCRIPTION_STATUS_CANCELED")]
        #pragma warning disable CS1591
        SUBSCRIPTION_STATUS_CANCELED,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUBSCRIPTION_STATUS_EXPIRED")]
        #pragma warning disable CS1591
        SUBSCRIPTION_STATUS_EXPIRED,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUBSCRIPTION_STATUS_PENDING")]
        #pragma warning disable CS1591
        SUBSCRIPTION_STATUS_PENDING,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUBSCRIPTION_STATUS_SUSPENDED")]
        #pragma warning disable CS1591
        SUBSCRIPTION_STATUS_SUSPENDED,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUBSCRIPTION_STATUS_TRIALING")]
        #pragma warning disable CS1591
        SUBSCRIPTION_STATUS_TRIALING,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUBSCRIPTION_STATUS_PAST_DUE")]
        #pragma warning disable CS1591
        SUBSCRIPTION_STATUS_PAST_DUE,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUBSCRIPTION_STATUS_UNPAID")]
        #pragma warning disable CS1591
        SUBSCRIPTION_STATUS_UNPAID,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUBSCRIPTION_STATUS_INCOMPLETE")]
        #pragma warning disable CS1591
        SUBSCRIPTION_STATUS_INCOMPLETE,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUBSCRIPTION_STATUS_INCOMPLETE_EXPIRED")]
        #pragma warning disable CS1591
        SUBSCRIPTION_STATUS_INCOMPLETE_EXPIRED,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUBSCRIPTION_STATUS_PAUSED")]
        #pragma warning disable CS1591
        SUBSCRIPTION_STATUS_PAUSED,
        #pragma warning restore CS1591
    }
}
