// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Rixl.Sdk.Models.Billing.V1
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TaxCalculationResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The amount_total property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? AmountTotal { get; set; }
#nullable restore
#else
        public UntypedNode AmountTotal { get; set; }
#endif
        /// <summary>The calculation_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CalculationId { get; set; }
#nullable restore
#else
        public string CalculationId { get; set; }
#endif
        /// <summary>The currency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>The tax_amount_exclusive property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? TaxAmountExclusive { get; set; }
#nullable restore
#else
        public UntypedNode TaxAmountExclusive { get; set; }
#endif
        /// <summary>The tax_amount_inclusive property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? TaxAmountInclusive { get; set; }
#nullable restore
#else
        public UntypedNode TaxAmountInclusive { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Models.Billing.V1.TaxCalculationResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Rixl.Sdk.Models.Billing.V1.TaxCalculationResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Rixl.Sdk.Models.Billing.V1.TaxCalculationResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount_total", n => { AmountTotal = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "calculation_id", n => { CalculationId = n.GetStringValue(); } },
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "tax_amount_exclusive", n => { TaxAmountExclusive = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "tax_amount_inclusive", n => { TaxAmountInclusive = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UntypedNode>("amount_total", AmountTotal);
            writer.WriteStringValue("calculation_id", CalculationId);
            writer.WriteStringValue("currency", Currency);
            writer.WriteObjectValue<UntypedNode>("tax_amount_exclusive", TaxAmountExclusive);
            writer.WriteObjectValue<UntypedNode>("tax_amount_inclusive", TaxAmountInclusive);
        }
    }
}
#pragma warning restore CS0618
