// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Rixl.Sdk.Models.Gateway
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UpdateVisibilityBody_visibility
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "public")]
        #pragma warning disable CS1591
        Public,
        #pragma warning restore CS1591
        [EnumMember(Value = "unlisted")]
        #pragma warning disable CS1591
        Unlisted,
        #pragma warning restore CS1591
        [EnumMember(Value = "private")]
        #pragma warning disable CS1591
        Private,
        #pragma warning restore CS1591
    }
}
