// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Rixl.Sdk.Models.Github_com_rixlhq_api_db_sqlc
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum VideoQuality
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "basic")]
        #pragma warning disable CS1591
        Basic,
        #pragma warning restore CS1591
        [EnumMember(Value = "shorts")]
        #pragma warning disable CS1591
        Shorts,
        #pragma warning restore CS1591
        [EnumMember(Value = "pro")]
        #pragma warning disable CS1591
        Pro,
        #pragma warning restore CS1591
    }
}
