// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Rixl.Sdk.Models.Posts.V1;
using Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.Creators;
using Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.Item;
using Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.Upload;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts
{
    /// <summary>
    /// Builds and executes requests for operations under \posts\v1\projects\{project_id}\feeds\{feed_id}\posts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PostsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The creators property</summary>
        public global::Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.Creators.CreatorsRequestBuilder Creators
        {
            get => new global::Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.Creators.CreatorsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The upload property</summary>
        public global::Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.Upload.UploadRequestBuilder Upload
        {
            get => new global::Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.Upload.UploadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Rixl.Sdk.posts.v1.projects.item.feeds.item.posts.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.Item.WithPost_ItemRequestBuilder"/></returns>
        public global::Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.Item.WithPost_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("post_id", position);
                return new global::Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.Item.WithPost_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.PostsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PostsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/posts/v1/projects/{project_id}/feeds/{feed_id}/posts{?creator_id*,pagination%2Elimit*,pagination%2Eoffset*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.PostsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PostsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/posts/v1/projects/{project_id}/feeds/{feed_id}/posts{?creator_id*,pagination%2Elimit*,pagination%2Eoffset*}", rawUrl)
        {
        }
        /// <summary>
        /// ListPosts
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Models.Posts.V1.ListPostsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Rixl.Sdk.Models.Posts.V1.ListPostsResponse?> GetAsync(Action<RequestConfiguration<global::Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.PostsRequestBuilder.PostsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Rixl.Sdk.Models.Posts.V1.ListPostsResponse> GetAsync(Action<RequestConfiguration<global::Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.PostsRequestBuilder.PostsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Rixl.Sdk.Models.Posts.V1.ListPostsResponse>(requestInfo, global::Rixl.Sdk.Models.Posts.V1.ListPostsResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// CreatePost
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Models.Posts.V1.Post"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Rixl.Sdk.Models.Posts.V1.Post?> PostAsync(global::Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.PostsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Rixl.Sdk.Models.Posts.V1.Post> PostAsync(global::Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.PostsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Rixl.Sdk.Models.Posts.V1.Post>(requestInfo, global::Rixl.Sdk.Models.Posts.V1.Post.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// ListPosts
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.PostsRequestBuilder.PostsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.PostsRequestBuilder.PostsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// CreatePost
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.PostsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.PostsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.PostsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.PostsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.PostsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// ListPosts
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PostsRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("creator_id")]
            public string? CreatorId { get; set; }
#nullable restore
#else
            [QueryParameter("creator_id")]
            public string CreatorId { get; set; }
#endif
            /// <summary>Maximum number of items to return.</summary>
            [QueryParameter("pagination%2Elimit")]
            public int? PaginationLimit { get; set; }
            /// <summary>Number of items to skip before collecting the result set.</summary>
            [QueryParameter("pagination%2Eoffset")]
            public int? PaginationOffset { get; set; }
        }
    }
}
#pragma warning restore CS0618
