// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Rixl.Sdk.Billing.V1.Tax.Calculate;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Rixl.Sdk.Billing.V1.Tax
{
    /// <summary>
    /// Builds and executes requests for operations under \billing\v1\tax
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TaxRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The calculate property</summary>
        public global::Rixl.Sdk.Billing.V1.Tax.Calculate.CalculateRequestBuilder Calculate
        {
            get => new global::Rixl.Sdk.Billing.V1.Tax.Calculate.CalculateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Billing.V1.Tax.TaxRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TaxRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/billing/v1/tax", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Billing.V1.Tax.TaxRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TaxRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/billing/v1/tax", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
