// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Rixl.Sdk.Analytics.V1.Top.Feeds;
using Rixl.Sdk.Analytics.V1.Top.Posts;
using Rixl.Sdk.Analytics.V1.Top.Videos;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Rixl.Sdk.Analytics.V1.Top
{
    /// <summary>
    /// Builds and executes requests for operations under \analytics\v1\top
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TopRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The feeds property</summary>
        public global::Rixl.Sdk.Analytics.V1.Top.Feeds.FeedsRequestBuilder Feeds
        {
            get => new global::Rixl.Sdk.Analytics.V1.Top.Feeds.FeedsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The posts property</summary>
        public global::Rixl.Sdk.Analytics.V1.Top.Posts.PostsRequestBuilder Posts
        {
            get => new global::Rixl.Sdk.Analytics.V1.Top.Posts.PostsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The videos property</summary>
        public global::Rixl.Sdk.Analytics.V1.Top.Videos.VideosRequestBuilder Videos
        {
            get => new global::Rixl.Sdk.Analytics.V1.Top.Videos.VideosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Analytics.V1.Top.TopRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TopRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/analytics/v1/top", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Analytics.V1.Top.TopRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TopRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/analytics/v1/top", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
