// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Rixl.Sdk.Models.Common.V1;
using System.Collections.Generic;
using System.IO;
using System;
namespace Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.Upload.Init
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InitPostRequestBody : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The contentType property</summary>
        public global::Rixl.Sdk.Models.Common.V1.MediaType? ContentType { get; set; }
        /// <summary>The creatorId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatorId { get; set; }
#nullable restore
#else
        public string CreatorId { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The fileName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FileName { get; set; }
#nullable restore
#else
        public string FileName { get; set; }
#endif
        /// <summary>The format property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Format { get; set; }
#nullable restore
#else
        public string Format { get; set; }
#endif
        /// <summary>The imageFormat property</summary>
        public global::Rixl.Sdk.Models.Common.V1.ImageFormat? ImageFormat { get; set; }
        /// <summary>The orgId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrgId { get; set; }
#nullable restore
#else
        public string OrgId { get; set; }
#endif
        /// <summary>The videoQuality property</summary>
        public global::Rixl.Sdk.Models.Common.V1.VideoQuality? VideoQuality { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.Upload.Init.InitPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.Upload.Init.InitPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Rixl.Sdk.Posts.V1.Projects.Item.Feeds.Item.Posts.Upload.Init.InitPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "contentType", n => { ContentType = n.GetEnumValue<global::Rixl.Sdk.Models.Common.V1.MediaType>(); } },
                { "creatorId", n => { CreatorId = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "fileName", n => { FileName = n.GetStringValue(); } },
                { "format", n => { Format = n.GetStringValue(); } },
                { "imageFormat", n => { ImageFormat = n.GetEnumValue<global::Rixl.Sdk.Models.Common.V1.ImageFormat>(); } },
                { "orgId", n => { OrgId = n.GetStringValue(); } },
                { "videoQuality", n => { VideoQuality = n.GetEnumValue<global::Rixl.Sdk.Models.Common.V1.VideoQuality>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Rixl.Sdk.Models.Common.V1.MediaType>("contentType", ContentType);
            writer.WriteStringValue("creatorId", CreatorId);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("fileName", FileName);
            writer.WriteStringValue("format", Format);
            writer.WriteEnumValue<global::Rixl.Sdk.Models.Common.V1.ImageFormat>("imageFormat", ImageFormat);
            writer.WriteStringValue("orgId", OrgId);
            writer.WriteEnumValue<global::Rixl.Sdk.Models.Common.V1.VideoQuality>("videoQuality", VideoQuality);
        }
    }
}
#pragma warning restore CS0618
