// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Rixl.Sdk.Media.V1.Projects.Item.Videos.Item.AudioTracks;
using Rixl.Sdk.Media.V1.Projects.Item.Videos.Item.Chapters;
using Rixl.Sdk.Media.V1.Projects.Item.Videos.Item.Subtitles;
using Rixl.Sdk.Media.V1.Projects.Item.Videos.Item.Visibility;
using Rixl.Sdk.Models.Google.Protobuf;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Rixl.Sdk.Media.V1.Projects.Item.Videos.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \media\v1\projects\{project_id}\videos\{video_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithVideo_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The audioTracks property</summary>
        public global::Rixl.Sdk.Media.V1.Projects.Item.Videos.Item.AudioTracks.AudioTracksRequestBuilder AudioTracks
        {
            get => new global::Rixl.Sdk.Media.V1.Projects.Item.Videos.Item.AudioTracks.AudioTracksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The chapters property</summary>
        public global::Rixl.Sdk.Media.V1.Projects.Item.Videos.Item.Chapters.ChaptersRequestBuilder Chapters
        {
            get => new global::Rixl.Sdk.Media.V1.Projects.Item.Videos.Item.Chapters.ChaptersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subtitles property</summary>
        public global::Rixl.Sdk.Media.V1.Projects.Item.Videos.Item.Subtitles.SubtitlesRequestBuilder Subtitles
        {
            get => new global::Rixl.Sdk.Media.V1.Projects.Item.Videos.Item.Subtitles.SubtitlesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The visibility property</summary>
        public global::Rixl.Sdk.Media.V1.Projects.Item.Videos.Item.Visibility.VisibilityRequestBuilder Visibility
        {
            get => new global::Rixl.Sdk.Media.V1.Projects.Item.Videos.Item.Visibility.VisibilityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Media.V1.Projects.Item.Videos.Item.WithVideo_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithVideo_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/v1/projects/{project_id}/videos/{video_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Media.V1.Projects.Item.Videos.Item.WithVideo_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithVideo_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/v1/projects/{project_id}/videos/{video_id}", rawUrl)
        {
        }
        /// <summary>
        /// DeleteVideo
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Models.Google.Protobuf.Empty"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Rixl.Sdk.Models.Google.Protobuf.Empty?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Rixl.Sdk.Models.Google.Protobuf.Empty> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Rixl.Sdk.Models.Google.Protobuf.Empty>(requestInfo, global::Rixl.Sdk.Models.Google.Protobuf.Empty.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// DeleteVideo
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Media.V1.Projects.Item.Videos.Item.WithVideo_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Rixl.Sdk.Media.V1.Projects.Item.Videos.Item.WithVideo_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Rixl.Sdk.Media.V1.Projects.Item.Videos.Item.WithVideo_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
