// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Rixl.Sdk.Models.Github_com_rixlhq_api_internal_videos_handler_upload
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InitResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The poster_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PosterId { get; set; }
#nullable restore
#else
        public string PosterId { get; set; }
#endif
        /// <summary>The poster_presigned_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PosterPresignedUrl { get; set; }
#nullable restore
#else
        public string PosterPresignedUrl { get; set; }
#endif
        /// <summary>The upload_expires property</summary>
        public int? UploadExpires { get; set; }
        /// <summary>The video_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VideoId { get; set; }
#nullable restore
#else
        public string VideoId { get; set; }
#endif
        /// <summary>The video_presigned_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VideoPresignedUrl { get; set; }
#nullable restore
#else
        public string VideoPresignedUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Models.Github_com_rixlhq_api_internal_videos_handler_upload.InitResponse"/> and sets the default values.
        /// </summary>
        public InitResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Models.Github_com_rixlhq_api_internal_videos_handler_upload.InitResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Rixl.Sdk.Models.Github_com_rixlhq_api_internal_videos_handler_upload.InitResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Rixl.Sdk.Models.Github_com_rixlhq_api_internal_videos_handler_upload.InitResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "poster_id", n => { PosterId = n.GetStringValue(); } },
                { "poster_presigned_url", n => { PosterPresignedUrl = n.GetStringValue(); } },
                { "upload_expires", n => { UploadExpires = n.GetIntValue(); } },
                { "video_id", n => { VideoId = n.GetStringValue(); } },
                { "video_presigned_url", n => { VideoPresignedUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("poster_id", PosterId);
            writer.WriteStringValue("poster_presigned_url", PosterPresignedUrl);
            writer.WriteIntValue("upload_expires", UploadExpires);
            writer.WriteStringValue("video_id", VideoId);
            writer.WriteStringValue("video_presigned_url", VideoPresignedUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
