// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Rixl.Sdk.Models.Github_com_rixlhq_api_internal_errors;
using Rixl.Sdk.Models.Internal_images_handler;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Rixl.Sdk.Media.Images.Upload.Init
{
    /// <summary>
    /// Builds and executes requests for operations under \media\images\upload\init
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InitRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Media.Images.Upload.Init.InitRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InitRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/images/upload/init", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Media.Images.Upload.Init.InitRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InitRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/images/upload/init", rawUrl)
        {
        }
        /// <summary>
        /// Initialize a presigned URL upload for an image file.
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Models.Internal_images_handler.InitResponse"/></returns>
        /// <param name="body">Upload initialization request</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Rixl.Sdk.Models.Github_com_rixlhq_api_internal_errors.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Rixl.Sdk.Models.Github_com_rixlhq_api_internal_errors.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Rixl.Sdk.Models.Github_com_rixlhq_api_internal_errors.ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Rixl.Sdk.Models.Github_com_rixlhq_api_internal_errors.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Rixl.Sdk.Models.Internal_images_handler.InitResponse?> PostAsync(global::Rixl.Sdk.Models.Internal_images_handler.UploadInitRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Rixl.Sdk.Models.Internal_images_handler.InitResponse> PostAsync(global::Rixl.Sdk.Models.Internal_images_handler.UploadInitRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Rixl.Sdk.Models.Github_com_rixlhq_api_internal_errors.ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Rixl.Sdk.Models.Github_com_rixlhq_api_internal_errors.ErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Rixl.Sdk.Models.Github_com_rixlhq_api_internal_errors.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Rixl.Sdk.Models.Github_com_rixlhq_api_internal_errors.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Rixl.Sdk.Models.Internal_images_handler.InitResponse>(requestInfo, global::Rixl.Sdk.Models.Internal_images_handler.InitResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Initialize a presigned URL upload for an image file.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Upload initialization request</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Rixl.Sdk.Models.Internal_images_handler.UploadInitRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Rixl.Sdk.Models.Internal_images_handler.UploadInitRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Media.Images.Upload.Init.InitRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Rixl.Sdk.Media.Images.Upload.Init.InitRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Rixl.Sdk.Media.Images.Upload.Init.InitRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
