// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Rixl.Sdk.Billing.V1.Address;
using Rixl.Sdk.Billing.V1.BandwidthUsage;
using Rixl.Sdk.Billing.V1.Checkout;
using Rixl.Sdk.Billing.V1.ContactSales;
using Rixl.Sdk.Billing.V1.Invoices;
using Rixl.Sdk.Billing.V1.Jobs;
using Rixl.Sdk.Billing.V1.PaymentMethods;
using Rixl.Sdk.Billing.V1.Plans;
using Rixl.Sdk.Billing.V1.SetupIntent;
using Rixl.Sdk.Billing.V1.StorageUsage;
using Rixl.Sdk.Billing.V1.Subscription;
using Rixl.Sdk.Billing.V1.Tax;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Rixl.Sdk.Billing.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \billing\v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The address property</summary>
        public global::Rixl.Sdk.Billing.V1.Address.AddressRequestBuilder Address
        {
            get => new global::Rixl.Sdk.Billing.V1.Address.AddressRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The bandwidthUsage property</summary>
        public global::Rixl.Sdk.Billing.V1.BandwidthUsage.BandwidthUsageRequestBuilder BandwidthUsage
        {
            get => new global::Rixl.Sdk.Billing.V1.BandwidthUsage.BandwidthUsageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The checkout property</summary>
        public global::Rixl.Sdk.Billing.V1.Checkout.CheckoutRequestBuilder Checkout
        {
            get => new global::Rixl.Sdk.Billing.V1.Checkout.CheckoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The contactSales property</summary>
        public global::Rixl.Sdk.Billing.V1.ContactSales.ContactSalesRequestBuilder ContactSales
        {
            get => new global::Rixl.Sdk.Billing.V1.ContactSales.ContactSalesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The invoices property</summary>
        public global::Rixl.Sdk.Billing.V1.Invoices.InvoicesRequestBuilder Invoices
        {
            get => new global::Rixl.Sdk.Billing.V1.Invoices.InvoicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The jobs property</summary>
        public global::Rixl.Sdk.Billing.V1.Jobs.JobsRequestBuilder Jobs
        {
            get => new global::Rixl.Sdk.Billing.V1.Jobs.JobsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The paymentMethods property</summary>
        public global::Rixl.Sdk.Billing.V1.PaymentMethods.PaymentMethodsRequestBuilder PaymentMethods
        {
            get => new global::Rixl.Sdk.Billing.V1.PaymentMethods.PaymentMethodsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The plans property</summary>
        public global::Rixl.Sdk.Billing.V1.Plans.PlansRequestBuilder Plans
        {
            get => new global::Rixl.Sdk.Billing.V1.Plans.PlansRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The setupIntent property</summary>
        public global::Rixl.Sdk.Billing.V1.SetupIntent.SetupIntentRequestBuilder SetupIntent
        {
            get => new global::Rixl.Sdk.Billing.V1.SetupIntent.SetupIntentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The storageUsage property</summary>
        public global::Rixl.Sdk.Billing.V1.StorageUsage.StorageUsageRequestBuilder StorageUsage
        {
            get => new global::Rixl.Sdk.Billing.V1.StorageUsage.StorageUsageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subscription property</summary>
        public global::Rixl.Sdk.Billing.V1.Subscription.SubscriptionRequestBuilder Subscription
        {
            get => new global::Rixl.Sdk.Billing.V1.Subscription.SubscriptionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tax property</summary>
        public global::Rixl.Sdk.Billing.V1.Tax.TaxRequestBuilder Tax
        {
            get => new global::Rixl.Sdk.Billing.V1.Tax.TaxRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Billing.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/billing/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Billing.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/billing/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
