// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Rixl.Sdk.Auth.V1.Users.Current.Totp.BackupCodes.Regenerate;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Rixl.Sdk.Auth.V1.Users.Current.Totp.BackupCodes
{
    /// <summary>
    /// Builds and executes requests for operations under \auth\v1\users\current\totp\backup-codes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BackupCodesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The regenerate property</summary>
        public global::Rixl.Sdk.Auth.V1.Users.Current.Totp.BackupCodes.Regenerate.RegenerateRequestBuilder Regenerate
        {
            get => new global::Rixl.Sdk.Auth.V1.Users.Current.Totp.BackupCodes.Regenerate.RegenerateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Auth.V1.Users.Current.Totp.BackupCodes.BackupCodesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BackupCodesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth/v1/users/current/totp/backup-codes", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Auth.V1.Users.Current.Totp.BackupCodes.BackupCodesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BackupCodesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth/v1/users/current/totp/backup-codes", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
