// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Rixl.Sdk.Videos.Item.Subtitles.Language.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Rixl.Sdk.Videos.Item.Subtitles.Language
{
    /// <summary>
    /// Builds and executes requests for operations under \videos\{videoId}\subtitles\language
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LanguageRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Rixl.Sdk.videos.item.subtitles.language.item collection</summary>
        /// <param name="position">Language Code (BCP 47)</param>
        /// <returns>A <see cref="global::Rixl.Sdk.Videos.Item.Subtitles.Language.Item.WithLang_codeItemRequestBuilder"/></returns>
        public global::Rixl.Sdk.Videos.Item.Subtitles.Language.Item.WithLang_codeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("lang_code", position);
                return new global::Rixl.Sdk.Videos.Item.Subtitles.Language.Item.WithLang_codeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Videos.Item.Subtitles.Language.LanguageRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LanguageRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/videos/{videoId}/subtitles/language", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Videos.Item.Subtitles.Language.LanguageRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LanguageRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/videos/{videoId}/subtitles/language", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
