// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Rixl.Sdk.Models.Support.V1
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TicketPriority
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "TICKET_PRIORITY_UNSPECIFIED")]
        #pragma warning disable CS1591
        TICKET_PRIORITY_UNSPECIFIED,
        #pragma warning restore CS1591
        [EnumMember(Value = "TICKET_PRIORITY_LOW")]
        #pragma warning disable CS1591
        TICKET_PRIORITY_LOW,
        #pragma warning restore CS1591
        [EnumMember(Value = "TICKET_PRIORITY_NORMAL")]
        #pragma warning disable CS1591
        TICKET_PRIORITY_NORMAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "TICKET_PRIORITY_HIGH")]
        #pragma warning disable CS1591
        TICKET_PRIORITY_HIGH,
        #pragma warning restore CS1591
        [EnumMember(Value = "TICKET_PRIORITY_URGENT")]
        #pragma warning disable CS1591
        TICKET_PRIORITY_URGENT,
        #pragma warning restore CS1591
    }
}
