// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Rixl.Sdk.Models.Analyticsv1;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Rixl.Sdk.Analytics.V1.Funnels
{
    /// <summary>
    /// Builds and executes requests for operations under \analytics\v1\funnels
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FunnelsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Analytics.V1.Funnels.FunnelsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FunnelsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/analytics/v1/funnels{?end*,start*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Analytics.V1.Funnels.FunnelsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FunnelsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/analytics/v1/funnels{?end*,start*}", rawUrl)
        {
        }
        /// <summary>
        /// Calculate funnel conversion across a sequence of steps
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Models.Analyticsv1.FunnelAnalytics"/></returns>
        /// <param name="body">Funnel definition</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Rixl.Sdk.Models.Analyticsv1.FunnelAnalytics?> PostAsync(global::Rixl.Sdk.Models.Analyticsv1.FunnelRequest body, Action<RequestConfiguration<global::Rixl.Sdk.Analytics.V1.Funnels.FunnelsRequestBuilder.FunnelsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Rixl.Sdk.Models.Analyticsv1.FunnelAnalytics> PostAsync(global::Rixl.Sdk.Models.Analyticsv1.FunnelRequest body, Action<RequestConfiguration<global::Rixl.Sdk.Analytics.V1.Funnels.FunnelsRequestBuilder.FunnelsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Rixl.Sdk.Models.Analyticsv1.FunnelAnalytics>(requestInfo, global::Rixl.Sdk.Models.Analyticsv1.FunnelAnalytics.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Calculate funnel conversion across a sequence of steps
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Funnel definition</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Rixl.Sdk.Models.Analyticsv1.FunnelRequest body, Action<RequestConfiguration<global::Rixl.Sdk.Analytics.V1.Funnels.FunnelsRequestBuilder.FunnelsRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Rixl.Sdk.Models.Analyticsv1.FunnelRequest body, Action<RequestConfiguration<global::Rixl.Sdk.Analytics.V1.Funnels.FunnelsRequestBuilder.FunnelsRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Analytics.V1.Funnels.FunnelsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Rixl.Sdk.Analytics.V1.Funnels.FunnelsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Rixl.Sdk.Analytics.V1.Funnels.FunnelsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Calculate funnel conversion across a sequence of steps
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FunnelsRequestBuilderPostQueryParameters 
        {
            /// <summary>End date (inclusive)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("end")]
            public string? End { get; set; }
#nullable restore
#else
            [QueryParameter("end")]
            public string End { get; set; }
#endif
            /// <summary>Start date (inclusive)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("start")]
            public string? Start { get; set; }
#nullable restore
#else
            [QueryParameter("start")]
            public string Start { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
