// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Rixl.Sdk.Media.Feeds.Item.Creators.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Rixl.Sdk.Media.Feeds.Item.Creators
{
    /// <summary>
    /// Builds and executes requests for operations under \media\feeds\{feedId}\creators
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreatorsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Rixl.Sdk.media.feeds.item.creators.item collection</summary>
        /// <param name="position">Creator ID</param>
        /// <returns>A <see cref="global::Rixl.Sdk.Media.Feeds.Item.Creators.Item.WithCreatorItemRequestBuilder"/></returns>
        public global::Rixl.Sdk.Media.Feeds.Item.Creators.Item.WithCreatorItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("creatorId", position);
                return new global::Rixl.Sdk.Media.Feeds.Item.Creators.Item.WithCreatorItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Media.Feeds.Item.Creators.CreatorsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CreatorsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/feeds/{feedId}/creators", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Media.Feeds.Item.Creators.CreatorsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CreatorsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/feeds/{feedId}/creators", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
