// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Rixl.Sdk.Models.Auth.V1
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AuthMethod
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "AUTH_METHOD_UNSPECIFIED")]
        #pragma warning disable CS1591
        AUTH_METHOD_UNSPECIFIED,
        #pragma warning restore CS1591
        [EnumMember(Value = "AUTH_METHOD_PASSKEY")]
        #pragma warning disable CS1591
        AUTH_METHOD_PASSKEY,
        #pragma warning restore CS1591
        [EnumMember(Value = "AUTH_METHOD_TOTP")]
        #pragma warning disable CS1591
        AUTH_METHOD_TOTP,
        #pragma warning restore CS1591
    }
}
