// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Rixl.Sdk.Models.Auth.V1
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MembershipRole
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "MEMBERSHIP_ROLE_UNSPECIFIED")]
        #pragma warning disable CS1591
        MEMBERSHIP_ROLE_UNSPECIFIED,
        #pragma warning restore CS1591
        [EnumMember(Value = "MEMBERSHIP_ROLE_OWNER")]
        #pragma warning disable CS1591
        MEMBERSHIP_ROLE_OWNER,
        #pragma warning restore CS1591
        [EnumMember(Value = "MEMBERSHIP_ROLE_ADMIN")]
        #pragma warning disable CS1591
        MEMBERSHIP_ROLE_ADMIN,
        #pragma warning restore CS1591
        [EnumMember(Value = "MEMBERSHIP_ROLE_MEMBER")]
        #pragma warning disable CS1591
        MEMBERSHIP_ROLE_MEMBER,
        #pragma warning restore CS1591
    }
}
