// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Rixl.Sdk.Models.Auth.V1
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Membership : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The joined_at property</summary>
        public DateTimeOffset? JoinedAt { get; set; }
        /// <summary>The organization_first_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationFirstName { get; set; }
#nullable restore
#else
        public string OrganizationFirstName { get; set; }
#endif
        /// <summary>The organization_last_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationLastName { get; set; }
#nullable restore
#else
        public string OrganizationLastName { get; set; }
#endif
        /// <summary>The organization_username property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationUsername { get; set; }
#nullable restore
#else
        public string OrganizationUsername { get; set; }
#endif
        /// <summary>The org_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrgId { get; set; }
#nullable restore
#else
        public string OrgId { get; set; }
#endif
        /// <summary>The role property</summary>
        public global::Rixl.Sdk.Models.Auth.V1.MembershipRole? Role { get; set; }
        /// <summary>The state property</summary>
        public global::Rixl.Sdk.Models.Auth.V1.MembershipState? State { get; set; }
        /// <summary>The user_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Models.Auth.V1.Membership"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Rixl.Sdk.Models.Auth.V1.Membership CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Rixl.Sdk.Models.Auth.V1.Membership();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetStringValue(); } },
                { "joined_at", n => { JoinedAt = n.GetDateTimeOffsetValue(); } },
                { "org_id", n => { OrgId = n.GetStringValue(); } },
                { "organization_first_name", n => { OrganizationFirstName = n.GetStringValue(); } },
                { "organization_last_name", n => { OrganizationLastName = n.GetStringValue(); } },
                { "organization_username", n => { OrganizationUsername = n.GetStringValue(); } },
                { "role", n => { Role = n.GetEnumValue<global::Rixl.Sdk.Models.Auth.V1.MembershipRole>(); } },
                { "state", n => { State = n.GetEnumValue<global::Rixl.Sdk.Models.Auth.V1.MembershipState>(); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("id", Id);
            writer.WriteDateTimeOffsetValue("joined_at", JoinedAt);
            writer.WriteStringValue("organization_first_name", OrganizationFirstName);
            writer.WriteStringValue("organization_last_name", OrganizationLastName);
            writer.WriteStringValue("organization_username", OrganizationUsername);
            writer.WriteStringValue("org_id", OrgId);
            writer.WriteEnumValue<global::Rixl.Sdk.Models.Auth.V1.MembershipRole>("role", Role);
            writer.WriteEnumValue<global::Rixl.Sdk.Models.Auth.V1.MembershipState>("state", State);
            writer.WriteStringValue("user_id", UserId);
        }
    }
}
#pragma warning restore CS0618
