// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Rixl.Sdk.Auth.V1.Users.Current.Passkeys.Item;
using Rixl.Sdk.Auth.V1.Users.Current.Passkeys.Register;
using Rixl.Sdk.Models.Authv1;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Rixl.Sdk.Auth.V1.Users.Current.Passkeys
{
    /// <summary>
    /// Builds and executes requests for operations under \auth\v1\users\current\passkeys
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PasskeysRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The register property</summary>
        public global::Rixl.Sdk.Auth.V1.Users.Current.Passkeys.Register.RegisterRequestBuilder Register
        {
            get => new global::Rixl.Sdk.Auth.V1.Users.Current.Passkeys.Register.RegisterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Rixl.Sdk.auth.v1.users.current.passkeys.item collection</summary>
        /// <param name="position">Passkey ID</param>
        /// <returns>A <see cref="global::Rixl.Sdk.Auth.V1.Users.Current.Passkeys.Item.PasskeysItemRequestBuilder"/></returns>
        public global::Rixl.Sdk.Auth.V1.Users.Current.Passkeys.Item.PasskeysItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Rixl.Sdk.Auth.V1.Users.Current.Passkeys.Item.PasskeysItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Auth.V1.Users.Current.Passkeys.PasskeysRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PasskeysRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth/v1/users/current/passkeys", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Auth.V1.Users.Current.Passkeys.PasskeysRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PasskeysRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth/v1/users/current/passkeys", rawUrl)
        {
        }
        /// <summary>
        /// Returns all passkeys registered to the authenticated user.
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Models.Authv1.ListPasskeysResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Rixl.Sdk.Models.Authv1.ListPasskeysResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Rixl.Sdk.Models.Authv1.ListPasskeysResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Rixl.Sdk.Models.Authv1.ListPasskeysResponse>(requestInfo, global::Rixl.Sdk.Models.Authv1.ListPasskeysResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns all passkeys registered to the authenticated user.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Auth.V1.Users.Current.Passkeys.PasskeysRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Rixl.Sdk.Auth.V1.Users.Current.Passkeys.PasskeysRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Rixl.Sdk.Auth.V1.Users.Current.Passkeys.PasskeysRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
