// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Rixl.Sdk.Models.Analytics.V1
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ContentViewEvent_view_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "start")]
        #pragma warning disable CS1591
        Start,
        #pragma warning restore CS1591
        [EnumMember(Value = "watch")]
        #pragma warning disable CS1591
        Watch,
        #pragma warning restore CS1591
        [EnumMember(Value = "end")]
        #pragma warning disable CS1591
        End,
        #pragma warning restore CS1591
    }
}
