// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Rixl.Sdk.Models.Analytics.V1
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FeedStats : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The avgTimePerVisitMs property</summary>
        public double? AvgTimePerVisitMs { get; set; }
        /// <summary>The feedId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FeedId { get; set; }
#nullable restore
#else
        public string FeedId { get; set; }
#endif
        /// <summary>The totalPosts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? TotalPosts { get; set; }
#nullable restore
#else
        public UntypedNode TotalPosts { get; set; }
#endif
        /// <summary>The totalViews property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? TotalViews { get; set; }
#nullable restore
#else
        public UntypedNode TotalViews { get; set; }
#endif
        /// <summary>The totalWatchTimeMs property</summary>
        public double? TotalWatchTimeMs { get; set; }
        /// <summary>The uniqueViewers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? UniqueViewers { get; set; }
#nullable restore
#else
        public UntypedNode UniqueViewers { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Models.Analytics.V1.FeedStats"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Rixl.Sdk.Models.Analytics.V1.FeedStats CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Rixl.Sdk.Models.Analytics.V1.FeedStats();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "avgTimePerVisitMs", n => { AvgTimePerVisitMs = n.GetDoubleValue(); } },
                { "feedId", n => { FeedId = n.GetStringValue(); } },
                { "totalPosts", n => { TotalPosts = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "totalViews", n => { TotalViews = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "totalWatchTimeMs", n => { TotalWatchTimeMs = n.GetDoubleValue(); } },
                { "uniqueViewers", n => { UniqueViewers = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("avgTimePerVisitMs", AvgTimePerVisitMs);
            writer.WriteStringValue("feedId", FeedId);
            writer.WriteObjectValue<UntypedNode>("totalPosts", TotalPosts);
            writer.WriteObjectValue<UntypedNode>("totalViews", TotalViews);
            writer.WriteDoubleValue("totalWatchTimeMs", TotalWatchTimeMs);
            writer.WriteObjectValue<UntypedNode>("uniqueViewers", UniqueViewers);
        }
    }
}
#pragma warning restore CS0618
