// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Rixl.Sdk.Models.Analytics.V1
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FunnelAnalytics : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The averageTimeHours property</summary>
        public double? AverageTimeHours { get; set; }
        /// <summary>The completedUsers property</summary>
        public int? CompletedUsers { get; set; }
        /// <summary>The completionRate property</summary>
        public double? CompletionRate { get; set; }
        /// <summary>The steps property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Rixl.Sdk.Models.Analytics.V1.FunnelStepResult>? Steps { get; set; }
#nullable restore
#else
        public List<global::Rixl.Sdk.Models.Analytics.V1.FunnelStepResult> Steps { get; set; }
#endif
        /// <summary>The totalUsers property</summary>
        public int? TotalUsers { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Models.Analytics.V1.FunnelAnalytics"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Rixl.Sdk.Models.Analytics.V1.FunnelAnalytics CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Rixl.Sdk.Models.Analytics.V1.FunnelAnalytics();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "averageTimeHours", n => { AverageTimeHours = n.GetDoubleValue(); } },
                { "completedUsers", n => { CompletedUsers = n.GetIntValue(); } },
                { "completionRate", n => { CompletionRate = n.GetDoubleValue(); } },
                { "steps", n => { Steps = n.GetCollectionOfObjectValues<global::Rixl.Sdk.Models.Analytics.V1.FunnelStepResult>(global::Rixl.Sdk.Models.Analytics.V1.FunnelStepResult.CreateFromDiscriminatorValue)?.AsList(); } },
                { "totalUsers", n => { TotalUsers = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("averageTimeHours", AverageTimeHours);
            writer.WriteIntValue("completedUsers", CompletedUsers);
            writer.WriteDoubleValue("completionRate", CompletionRate);
            writer.WriteCollectionOfObjectValues<global::Rixl.Sdk.Models.Analytics.V1.FunnelStepResult>("steps", Steps);
            writer.WriteIntValue("totalUsers", TotalUsers);
        }
    }
}
#pragma warning restore CS0618
