// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Rixl.Sdk.Models.Analytics.V1
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SessionStartEvent : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The browser property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Browser { get; set; }
#nullable restore
#else
        public string Browser { get; set; }
#endif
        /// <summary>The color_depth property</summary>
        public double? ColorDepth { get; set; }
        /// <summary>The country property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Country { get; set; }
#nullable restore
#else
        public string Country { get; set; }
#endif
        /// <summary>The language property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Language { get; set; }
#nullable restore
#else
        public string Language { get; set; }
#endif
        /// <summary>The platform property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Platform { get; set; }
#nullable restore
#else
        public string Platform { get; set; }
#endif
        /// <summary>The screen_resolution property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScreenResolution { get; set; }
#nullable restore
#else
        public string ScreenResolution { get; set; }
#endif
        /// <summary>The tg_platform property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TgPlatform { get; set; }
#nullable restore
#else
        public string TgPlatform { get; set; }
#endif
        /// <summary>The tg_version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TgVersion { get; set; }
#nullable restore
#else
        public string TgVersion { get; set; }
#endif
        /// <summary>The timezone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Timezone { get; set; }
#nullable restore
#else
        public string Timezone { get; set; }
#endif
        /// <summary>The timezone_offset property</summary>
        public double? TimezoneOffset { get; set; }
        /// <summary>The touch_support property</summary>
        public bool? TouchSupport { get; set; }
        /// <summary>The user_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>The utm_campaign property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UtmCampaign { get; set; }
#nullable restore
#else
        public string UtmCampaign { get; set; }
#endif
        /// <summary>The utm_source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UtmSource { get; set; }
#nullable restore
#else
        public string UtmSource { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Models.Analytics.V1.SessionStartEvent"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Rixl.Sdk.Models.Analytics.V1.SessionStartEvent CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Rixl.Sdk.Models.Analytics.V1.SessionStartEvent();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "browser", n => { Browser = n.GetStringValue(); } },
                { "color_depth", n => { ColorDepth = n.GetDoubleValue(); } },
                { "country", n => { Country = n.GetStringValue(); } },
                { "language", n => { Language = n.GetStringValue(); } },
                { "platform", n => { Platform = n.GetStringValue(); } },
                { "screen_resolution", n => { ScreenResolution = n.GetStringValue(); } },
                { "tg_platform", n => { TgPlatform = n.GetStringValue(); } },
                { "tg_version", n => { TgVersion = n.GetStringValue(); } },
                { "timezone", n => { Timezone = n.GetStringValue(); } },
                { "timezone_offset", n => { TimezoneOffset = n.GetDoubleValue(); } },
                { "touch_support", n => { TouchSupport = n.GetBoolValue(); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
                { "utm_campaign", n => { UtmCampaign = n.GetStringValue(); } },
                { "utm_source", n => { UtmSource = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("browser", Browser);
            writer.WriteDoubleValue("color_depth", ColorDepth);
            writer.WriteStringValue("country", Country);
            writer.WriteStringValue("language", Language);
            writer.WriteStringValue("platform", Platform);
            writer.WriteStringValue("screen_resolution", ScreenResolution);
            writer.WriteStringValue("tg_platform", TgPlatform);
            writer.WriteStringValue("tg_version", TgVersion);
            writer.WriteStringValue("timezone", Timezone);
            writer.WriteDoubleValue("timezone_offset", TimezoneOffset);
            writer.WriteBoolValue("touch_support", TouchSupport);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteStringValue("utm_campaign", UtmCampaign);
            writer.WriteStringValue("utm_source", UtmSource);
        }
    }
}
#pragma warning restore CS0618
