// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Rixl.Sdk.Models.Github_com_rixlhq_api_db_sqlc;
using System.Collections.Generic;
using System.IO;
using System;
namespace Rixl.Sdk.Models.Github_com_rixlhq_api_internal_videos
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class VideoResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bitrate property</summary>
        public int? Bitrate { get; set; }
        /// <summary>The chapters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Rixl.Sdk.Models.Chapter>? Chapters { get; set; }
#nullable restore
#else
        public List<global::Rixl.Sdk.Models.Chapter> Chapters { get; set; }
#endif
        /// <summary>The codec property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Codec { get; set; }
#nullable restore
#else
        public string Codec { get; set; }
#endif
        /// <summary>The duration property</summary>
        public double? Duration { get; set; }
        /// <summary>The file property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Rixl.Sdk.Models.FileObject? File { get; set; }
#nullable restore
#else
        public global::Rixl.Sdk.Models.FileObject File { get; set; }
#endif
        /// <summary>The framerate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Framerate { get; set; }
#nullable restore
#else
        public string Framerate { get; set; }
#endif
        /// <summary>The hdr property</summary>
        public bool? Hdr { get; set; }
        /// <summary>The height property</summary>
        public int? Height { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The plan_type property</summary>
        public global::Rixl.Sdk.Models.Github_com_rixlhq_api_db_sqlc.PlanType? PlanType { get; set; }
        /// <summary>The poster property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Rixl.Sdk.Models.Image? Poster { get; set; }
#nullable restore
#else
        public global::Rixl.Sdk.Models.Image Poster { get; set; }
#endif
        /// <summary>The width property</summary>
        public int? Width { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Models.Github_com_rixlhq_api_internal_videos.VideoResponse"/> and sets the default values.
        /// </summary>
        public VideoResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Models.Github_com_rixlhq_api_internal_videos.VideoResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Rixl.Sdk.Models.Github_com_rixlhq_api_internal_videos.VideoResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Rixl.Sdk.Models.Github_com_rixlhq_api_internal_videos.VideoResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bitrate", n => { Bitrate = n.GetIntValue(); } },
                { "chapters", n => { Chapters = n.GetCollectionOfObjectValues<global::Rixl.Sdk.Models.Chapter>(global::Rixl.Sdk.Models.Chapter.CreateFromDiscriminatorValue)?.AsList(); } },
                { "codec", n => { Codec = n.GetStringValue(); } },
                { "duration", n => { Duration = n.GetDoubleValue(); } },
                { "file", n => { File = n.GetObjectValue<global::Rixl.Sdk.Models.FileObject>(global::Rixl.Sdk.Models.FileObject.CreateFromDiscriminatorValue); } },
                { "framerate", n => { Framerate = n.GetStringValue(); } },
                { "hdr", n => { Hdr = n.GetBoolValue(); } },
                { "height", n => { Height = n.GetIntValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "plan_type", n => { PlanType = n.GetEnumValue<global::Rixl.Sdk.Models.Github_com_rixlhq_api_db_sqlc.PlanType>(); } },
                { "poster", n => { Poster = n.GetObjectValue<global::Rixl.Sdk.Models.Image>(global::Rixl.Sdk.Models.Image.CreateFromDiscriminatorValue); } },
                { "width", n => { Width = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("bitrate", Bitrate);
            writer.WriteCollectionOfObjectValues<global::Rixl.Sdk.Models.Chapter>("chapters", Chapters);
            writer.WriteStringValue("codec", Codec);
            writer.WriteDoubleValue("duration", Duration);
            writer.WriteObjectValue<global::Rixl.Sdk.Models.FileObject>("file", File);
            writer.WriteStringValue("framerate", Framerate);
            writer.WriteBoolValue("hdr", Hdr);
            writer.WriteIntValue("height", Height);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Rixl.Sdk.Models.Github_com_rixlhq_api_db_sqlc.PlanType>("plan_type", PlanType);
            writer.WriteObjectValue<global::Rixl.Sdk.Models.Image>("poster", Poster);
            writer.WriteIntValue("width", Width);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
