// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Rixl.Sdk.Media.V1.Projects.Item.Videos.Item;
using Rixl.Sdk.Media.V1.Projects.Item.Videos.Upload;
using Rixl.Sdk.Models.Videos.V1;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Rixl.Sdk.Media.V1.Projects.Item.Videos
{
    /// <summary>
    /// Builds and executes requests for operations under \media\v1\projects\{project_id}\videos
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VideosRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The upload property</summary>
        public global::Rixl.Sdk.Media.V1.Projects.Item.Videos.Upload.UploadRequestBuilder Upload
        {
            get => new global::Rixl.Sdk.Media.V1.Projects.Item.Videos.Upload.UploadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Rixl.Sdk.media.v1.projects.item.videos.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Rixl.Sdk.Media.V1.Projects.Item.Videos.Item.WithVideo_ItemRequestBuilder"/></returns>
        public global::Rixl.Sdk.Media.V1.Projects.Item.Videos.Item.WithVideo_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("video_id", position);
                return new global::Rixl.Sdk.Media.V1.Projects.Item.Videos.Item.WithVideo_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Media.V1.Projects.Item.Videos.VideosRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VideosRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/v1/projects/{project_id}/videos{?pagination%2Elimit*,pagination%2Eoffset*,sortDirection*,sortField*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Media.V1.Projects.Item.Videos.VideosRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VideosRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/v1/projects/{project_id}/videos{?pagination%2Elimit*,pagination%2Eoffset*,sortDirection*,sortField*}", rawUrl)
        {
        }
        /// <summary>
        /// ListVideos
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Models.Videos.V1.ListVideosResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Rixl.Sdk.Models.Videos.V1.ListVideosResponse?> GetAsync(Action<RequestConfiguration<global::Rixl.Sdk.Media.V1.Projects.Item.Videos.VideosRequestBuilder.VideosRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Rixl.Sdk.Models.Videos.V1.ListVideosResponse> GetAsync(Action<RequestConfiguration<global::Rixl.Sdk.Media.V1.Projects.Item.Videos.VideosRequestBuilder.VideosRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Rixl.Sdk.Models.Videos.V1.ListVideosResponse>(requestInfo, global::Rixl.Sdk.Models.Videos.V1.ListVideosResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// ListVideos
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Rixl.Sdk.Media.V1.Projects.Item.Videos.VideosRequestBuilder.VideosRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Rixl.Sdk.Media.V1.Projects.Item.Videos.VideosRequestBuilder.VideosRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Media.V1.Projects.Item.Videos.VideosRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Rixl.Sdk.Media.V1.Projects.Item.Videos.VideosRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Rixl.Sdk.Media.V1.Projects.Item.Videos.VideosRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// ListVideos
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class VideosRequestBuilderGetQueryParameters 
        {
            /// <summary>Maximum number of items to return.</summary>
            [QueryParameter("pagination%2Elimit")]
            public int? PaginationLimit { get; set; }
            /// <summary>Number of items to skip before collecting the result set.</summary>
            [QueryParameter("pagination%2Eoffset")]
            public int? PaginationOffset { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sortDirection")]
            public string? SortDirection { get; set; }
#nullable restore
#else
            [QueryParameter("sortDirection")]
            public string SortDirection { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sortField")]
            public string? SortField { get; set; }
#nullable restore
#else
            [QueryParameter("sortField")]
            public string SortField { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
