// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Rixl.Sdk.Auth.V1.Memberships.Active;
using Rixl.Sdk.Auth.V1.Memberships.Item;
using Rixl.Sdk.Auth.V1.Memberships.Pending;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Rixl.Sdk.Auth.V1.Memberships
{
    /// <summary>
    /// Builds and executes requests for operations under \auth\v1\memberships
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MembershipsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The active property</summary>
        public global::Rixl.Sdk.Auth.V1.Memberships.Active.ActiveRequestBuilder Active
        {
            get => new global::Rixl.Sdk.Auth.V1.Memberships.Active.ActiveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pending property</summary>
        public global::Rixl.Sdk.Auth.V1.Memberships.Pending.PendingRequestBuilder Pending
        {
            get => new global::Rixl.Sdk.Auth.V1.Memberships.Pending.PendingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Rixl.Sdk.auth.v1.memberships.item collection</summary>
        /// <param name="position">Membership/organization ID</param>
        /// <returns>A <see cref="global::Rixl.Sdk.Auth.V1.Memberships.Item.WithOrgItemRequestBuilder"/></returns>
        public global::Rixl.Sdk.Auth.V1.Memberships.Item.WithOrgItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("orgId", position);
                return new global::Rixl.Sdk.Auth.V1.Memberships.Item.WithOrgItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Auth.V1.Memberships.MembershipsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MembershipsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth/v1/memberships", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Auth.V1.Memberships.MembershipsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MembershipsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth/v1/memberships", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
