// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Rixl.Sdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FileStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "uploading")]
        #pragma warning disable CS1591
        Uploading,
        #pragma warning restore CS1591
        [EnumMember(Value = "uploaded")]
        #pragma warning disable CS1591
        Uploaded,
        #pragma warning restore CS1591
        [EnumMember(Value = "processing")]
        #pragma warning disable CS1591
        Processing,
        #pragma warning restore CS1591
        [EnumMember(Value = "preparing")]
        #pragma warning disable CS1591
        Preparing,
        #pragma warning restore CS1591
        [EnumMember(Value = "ready")]
        #pragma warning disable CS1591
        Ready,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
    }
}
