// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Rixl.Sdk.Models.Clientauth.V1
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ClientCredentialStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "CLIENT_CREDENTIAL_STATUS_UNSPECIFIED")]
        #pragma warning disable CS1591
        CLIENT_CREDENTIAL_STATUS_UNSPECIFIED,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLIENT_CREDENTIAL_STATUS_ACTIVE")]
        #pragma warning disable CS1591
        CLIENT_CREDENTIAL_STATUS_ACTIVE,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLIENT_CREDENTIAL_STATUS_REVOKED")]
        #pragma warning disable CS1591
        CLIENT_CREDENTIAL_STATUS_REVOKED,
        #pragma warning restore CS1591
    }
}
