// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Rixl.Sdk.Models.Project.V1;
using Rixl.Sdk.Organizations.Item.Projects.V1.Item.CustomDomain;
using Rixl.Sdk.Organizations.Item.Projects.V1.Item.Move;
using Rixl.Sdk.Organizations.Item.Projects.V1.Item.Name;
using Rixl.Sdk.Organizations.Item.Projects.V1.Item.VideoQuality;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Rixl.Sdk.Organizations.Item.Projects.V1.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \organizations\{org_id}\projects\v1\{project_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithProject_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The customDomain property</summary>
        public global::Rixl.Sdk.Organizations.Item.Projects.V1.Item.CustomDomain.CustomDomainRequestBuilder CustomDomain
        {
            get => new global::Rixl.Sdk.Organizations.Item.Projects.V1.Item.CustomDomain.CustomDomainRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The move property</summary>
        public global::Rixl.Sdk.Organizations.Item.Projects.V1.Item.Move.MoveRequestBuilder Move
        {
            get => new global::Rixl.Sdk.Organizations.Item.Projects.V1.Item.Move.MoveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The name property</summary>
        public global::Rixl.Sdk.Organizations.Item.Projects.V1.Item.Name.NameRequestBuilder Name
        {
            get => new global::Rixl.Sdk.Organizations.Item.Projects.V1.Item.Name.NameRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The videoQuality property</summary>
        public global::Rixl.Sdk.Organizations.Item.Projects.V1.Item.VideoQuality.VideoQualityRequestBuilder VideoQuality
        {
            get => new global::Rixl.Sdk.Organizations.Item.Projects.V1.Item.VideoQuality.VideoQualityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Organizations.Item.Projects.V1.Item.WithProject_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProject_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/organizations/{org_id}/projects/v1/{project_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Organizations.Item.Projects.V1.Item.WithProject_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProject_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/organizations/{org_id}/projects/v1/{project_id}", rawUrl)
        {
        }
        /// <summary>
        /// DeleteProject
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Models.Project.V1.Project"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Rixl.Sdk.Models.Project.V1.Project?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Rixl.Sdk.Models.Project.V1.Project> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Rixl.Sdk.Models.Project.V1.Project>(requestInfo, global::Rixl.Sdk.Models.Project.V1.Project.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// GetProject
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Models.Project.V1.Project"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Rixl.Sdk.Models.Project.V1.Project?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Rixl.Sdk.Models.Project.V1.Project> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Rixl.Sdk.Models.Project.V1.Project>(requestInfo, global::Rixl.Sdk.Models.Project.V1.Project.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// DeleteProject
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// GetProject
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Organizations.Item.Projects.V1.Item.WithProject_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Rixl.Sdk.Organizations.Item.Projects.V1.Item.WithProject_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Rixl.Sdk.Organizations.Item.Projects.V1.Item.WithProject_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
