// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Rixl.Sdk.Models.Common.V1;
using Rixl.Sdk.Models.Images.V1;
using System.Collections.Generic;
using System.IO;
using System;
namespace Rixl.Sdk.Models.Videos.V1
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Video : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The bitrate property</summary>
        public int? Bitrate { get; set; }
        /// <summary>The codec property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Codec { get; set; }
#nullable restore
#else
        public string Codec { get; set; }
#endif
        /// <summary>The duration property</summary>
        public TimeSpan? Duration { get; set; }
        /// <summary>The file property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Rixl.Sdk.Models.Common.V1.FileObject? File { get; set; }
#nullable restore
#else
        public global::Rixl.Sdk.Models.Common.V1.FileObject File { get; set; }
#endif
        /// <summary>The framerate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Framerate { get; set; }
#nullable restore
#else
        public string Framerate { get; set; }
#endif
        /// <summary>The hdr property</summary>
        public bool? Hdr { get; set; }
        /// <summary>The height property</summary>
        public int? Height { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The poster property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Rixl.Sdk.Models.Images.V1.Image? Poster { get; set; }
#nullable restore
#else
        public global::Rixl.Sdk.Models.Images.V1.Image Poster { get; set; }
#endif
        /// <summary>The visibility property</summary>
        public global::Rixl.Sdk.Models.Common.V1.Visibility? Visibility { get; set; }
        /// <summary>The width property</summary>
        public int? Width { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Models.Videos.V1.Video"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Rixl.Sdk.Models.Videos.V1.Video CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Rixl.Sdk.Models.Videos.V1.Video();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bitrate", n => { Bitrate = n.GetIntValue(); } },
                { "codec", n => { Codec = n.GetStringValue(); } },
                { "duration", n => { Duration = n.GetTimeSpanValue(); } },
                { "file", n => { File = n.GetObjectValue<global::Rixl.Sdk.Models.Common.V1.FileObject>(global::Rixl.Sdk.Models.Common.V1.FileObject.CreateFromDiscriminatorValue); } },
                { "framerate", n => { Framerate = n.GetStringValue(); } },
                { "hdr", n => { Hdr = n.GetBoolValue(); } },
                { "height", n => { Height = n.GetIntValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "poster", n => { Poster = n.GetObjectValue<global::Rixl.Sdk.Models.Images.V1.Image>(global::Rixl.Sdk.Models.Images.V1.Image.CreateFromDiscriminatorValue); } },
                { "visibility", n => { Visibility = n.GetEnumValue<global::Rixl.Sdk.Models.Common.V1.Visibility>(); } },
                { "width", n => { Width = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("bitrate", Bitrate);
            writer.WriteStringValue("codec", Codec);
            writer.WriteTimeSpanValue("duration", Duration);
            writer.WriteObjectValue<global::Rixl.Sdk.Models.Common.V1.FileObject>("file", File);
            writer.WriteStringValue("framerate", Framerate);
            writer.WriteBoolValue("hdr", Hdr);
            writer.WriteIntValue("height", Height);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Rixl.Sdk.Models.Images.V1.Image>("poster", Poster);
            writer.WriteEnumValue<global::Rixl.Sdk.Models.Common.V1.Visibility>("visibility", Visibility);
            writer.WriteIntValue("width", Width);
        }
    }
}
#pragma warning restore CS0618
