// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Rixl.Sdk.Analytics.V1.Dashboard.ChartQuery;
using Rixl.Sdk.Analytics.V1.Dashboard.Datasets;
using Rixl.Sdk.Analytics.V1.Dashboard.FilterOptions;
using Rixl.Sdk.Models.Analytics.V1;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Rixl.Sdk.Analytics.V1.Dashboard
{
    /// <summary>
    /// Builds and executes requests for operations under \analytics\v1\dashboard
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DashboardRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The chartQuery property</summary>
        public global::Rixl.Sdk.Analytics.V1.Dashboard.ChartQuery.ChartQueryRequestBuilder ChartQuery
        {
            get => new global::Rixl.Sdk.Analytics.V1.Dashboard.ChartQuery.ChartQueryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The datasets property</summary>
        public global::Rixl.Sdk.Analytics.V1.Dashboard.Datasets.DatasetsRequestBuilder Datasets
        {
            get => new global::Rixl.Sdk.Analytics.V1.Dashboard.Datasets.DatasetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The filterOptions property</summary>
        public global::Rixl.Sdk.Analytics.V1.Dashboard.FilterOptions.FilterOptionsRequestBuilder FilterOptions
        {
            get => new global::Rixl.Sdk.Analytics.V1.Dashboard.FilterOptions.FilterOptionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Analytics.V1.Dashboard.DashboardRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DashboardRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/analytics/v1/dashboard?time_end={time_end}&time_start={time_start}{&filter%2Ebrowsers*,filter%2Ecities*,filter%2Ecountries*,filter%2Edevices*,filter%2Elanguages*,filter%2Eos*,filter%2Eos_versions*,filter%2Eregions*,interval*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Analytics.V1.Dashboard.DashboardRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DashboardRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/analytics/v1/dashboard?time_end={time_end}&time_start={time_start}{&filter%2Ebrowsers*,filter%2Ecities*,filter%2Ecountries*,filter%2Edevices*,filter%2Elanguages*,filter%2Eos*,filter%2Eos_versions*,filter%2Eregions*,interval*}", rawUrl)
        {
        }
        /// <summary>
        /// GetDashboardStats
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Models.Analytics.V1.DashboardStatsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Rixl.Sdk.Models.Analytics.V1.DashboardStatsResponse?> GetAsync(Action<RequestConfiguration<global::Rixl.Sdk.Analytics.V1.Dashboard.DashboardRequestBuilder.DashboardRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Rixl.Sdk.Models.Analytics.V1.DashboardStatsResponse> GetAsync(Action<RequestConfiguration<global::Rixl.Sdk.Analytics.V1.Dashboard.DashboardRequestBuilder.DashboardRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Rixl.Sdk.Models.Analytics.V1.DashboardStatsResponse>(requestInfo, global::Rixl.Sdk.Models.Analytics.V1.DashboardStatsResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// GetDashboardStats
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Rixl.Sdk.Analytics.V1.Dashboard.DashboardRequestBuilder.DashboardRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Rixl.Sdk.Analytics.V1.Dashboard.DashboardRequestBuilder.DashboardRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Analytics.V1.Dashboard.DashboardRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Rixl.Sdk.Analytics.V1.Dashboard.DashboardRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Rixl.Sdk.Analytics.V1.Dashboard.DashboardRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// GetDashboardStats
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DashboardRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%2Ebrowsers")]
            public string[]? FilterBrowsers { get; set; }
#nullable restore
#else
            [QueryParameter("filter%2Ebrowsers")]
            public string[] FilterBrowsers { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%2Ecities")]
            public string[]? FilterCities { get; set; }
#nullable restore
#else
            [QueryParameter("filter%2Ecities")]
            public string[] FilterCities { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%2Ecountries")]
            public string[]? FilterCountries { get; set; }
#nullable restore
#else
            [QueryParameter("filter%2Ecountries")]
            public string[] FilterCountries { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%2Edevices")]
            public string[]? FilterDevices { get; set; }
#nullable restore
#else
            [QueryParameter("filter%2Edevices")]
            public string[] FilterDevices { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%2Elanguages")]
            public string[]? FilterLanguages { get; set; }
#nullable restore
#else
            [QueryParameter("filter%2Elanguages")]
            public string[] FilterLanguages { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%2Eos")]
            public string[]? FilterOs { get; set; }
#nullable restore
#else
            [QueryParameter("filter%2Eos")]
            public string[] FilterOs { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%2Eos_versions")]
            public string[]? FilterOsVersions { get; set; }
#nullable restore
#else
            [QueryParameter("filter%2Eos_versions")]
            public string[] FilterOsVersions { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%2Eregions")]
            public string[]? FilterRegions { get; set; }
#nullable restore
#else
            [QueryParameter("filter%2Eregions")]
            public string[] FilterRegions { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("interval")]
            public string? Interval { get; set; }
#nullable restore
#else
            [QueryParameter("interval")]
            public string Interval { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("time_end")]
            public string? TimeEnd { get; set; }
#nullable restore
#else
            [QueryParameter("time_end")]
            public string TimeEnd { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("time_start")]
            public string? TimeStart { get; set; }
#nullable restore
#else
            [QueryParameter("time_start")]
            public string TimeStart { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
