// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Rixl.Sdk.Models.Analyticsv1;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Rixl.Sdk.Analytics.V1.Retention
{
    /// <summary>
    /// Builds and executes requests for operations under \analytics\v1\retention
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RetentionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Analytics.V1.Retention.RetentionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RetentionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/analytics/v1/retention{?end*,period*,start*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Analytics.V1.Retention.RetentionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RetentionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/analytics/v1/retention{?end*,period*,start*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns retention cohorts over a date range
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Models.Analyticsv1.RetentionAnalytics"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Rixl.Sdk.Models.Analyticsv1.RetentionAnalytics?> GetAsync(Action<RequestConfiguration<global::Rixl.Sdk.Analytics.V1.Retention.RetentionRequestBuilder.RetentionRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Rixl.Sdk.Models.Analyticsv1.RetentionAnalytics> GetAsync(Action<RequestConfiguration<global::Rixl.Sdk.Analytics.V1.Retention.RetentionRequestBuilder.RetentionRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Rixl.Sdk.Models.Analyticsv1.RetentionAnalytics>(requestInfo, global::Rixl.Sdk.Models.Analyticsv1.RetentionAnalytics.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns retention cohorts over a date range
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Rixl.Sdk.Analytics.V1.Retention.RetentionRequestBuilder.RetentionRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Rixl.Sdk.Analytics.V1.Retention.RetentionRequestBuilder.RetentionRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Analytics.V1.Retention.RetentionRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Rixl.Sdk.Analytics.V1.Retention.RetentionRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Rixl.Sdk.Analytics.V1.Retention.RetentionRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns retention cohorts over a date range
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RetentionRequestBuilderGetQueryParameters 
        {
            /// <summary>End date (inclusive)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("end")]
            public string? End { get; set; }
#nullable restore
#else
            [QueryParameter("end")]
            public string End { get; set; }
#endif
            /// <summary>Cohort period (day, week, month)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("period")]
            public string? Period { get; set; }
#nullable restore
#else
            [QueryParameter("period")]
            public string Period { get; set; }
#endif
            /// <summary>Start date (inclusive)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("start")]
            public string? Start { get; set; }
#nullable restore
#else
            [QueryParameter("start")]
            public string Start { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
