// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Rixl.Sdk.Models.Types
{
    /// <summary>
    /// Feed details
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateFeedRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The allow_images property</summary>
        public bool? AllowImages { get; set; }
        /// <summary>The allow_videos property</summary>
        public bool? AllowVideos { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The has_comments property</summary>
        public bool? HasComments { get; set; }
        /// <summary>The has_likes property</summary>
        public bool? HasLikes { get; set; }
        /// <summary>The has_shares property</summary>
        public bool? HasShares { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The project_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectId { get; set; }
#nullable restore
#else
        public string ProjectId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Models.Types.CreateFeedRequest"/> and sets the default values.
        /// </summary>
        public CreateFeedRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Rixl.Sdk.Models.Types.CreateFeedRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Rixl.Sdk.Models.Types.CreateFeedRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Rixl.Sdk.Models.Types.CreateFeedRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allow_images", n => { AllowImages = n.GetBoolValue(); } },
                { "allow_videos", n => { AllowVideos = n.GetBoolValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "has_comments", n => { HasComments = n.GetBoolValue(); } },
                { "has_likes", n => { HasLikes = n.GetBoolValue(); } },
                { "has_shares", n => { HasShares = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "project_id", n => { ProjectId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allow_images", AllowImages);
            writer.WriteBoolValue("allow_videos", AllowVideos);
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("has_comments", HasComments);
            writer.WriteBoolValue("has_likes", HasLikes);
            writer.WriteBoolValue("has_shares", HasShares);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("project_id", ProjectId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
