// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Rixl.Sdk.Media.Videos.Item;
using Rixl.Sdk.Media.Videos.Languages;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Rixl.Sdk.Media.Videos
{
    /// <summary>
    /// Builds and executes requests for operations under \media\videos
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VideosRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The languages property</summary>
        public global::Rixl.Sdk.Media.Videos.Languages.LanguagesRequestBuilder Languages
        {
            get => new global::Rixl.Sdk.Media.Videos.Languages.LanguagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Rixl.Sdk.media.videos.item collection</summary>
        /// <param name="position">Video ID</param>
        /// <returns>A <see cref="global::Rixl.Sdk.Media.Videos.Item.WithVideoItemRequestBuilder"/></returns>
        public global::Rixl.Sdk.Media.Videos.Item.WithVideoItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("videoId", position);
                return new global::Rixl.Sdk.Media.Videos.Item.WithVideoItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Media.Videos.VideosRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VideosRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/videos", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Media.Videos.VideosRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VideosRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/videos", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
