// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Rixl.Sdk.Media.V1.Projects.Item.Images;
using Rixl.Sdk.Media.V1.Projects.Item.Videos;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Rixl.Sdk.Media.V1.Projects.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \media\v1\projects\{projectId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithProjectItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The images property</summary>
        public global::Rixl.Sdk.Media.V1.Projects.Item.Images.ImagesRequestBuilder Images
        {
            get => new global::Rixl.Sdk.Media.V1.Projects.Item.Images.ImagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The videos property</summary>
        public global::Rixl.Sdk.Media.V1.Projects.Item.Videos.VideosRequestBuilder Videos
        {
            get => new global::Rixl.Sdk.Media.V1.Projects.Item.Videos.VideosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Media.V1.Projects.Item.WithProjectItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProjectItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/v1/projects/{projectId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Media.V1.Projects.Item.WithProjectItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProjectItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/v1/projects/{projectId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
