// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Rixl.Sdk.Support.V1.Categories;
using Rixl.Sdk.Support.V1.Chat;
using Rixl.Sdk.Support.V1.Tickets;
using Rixl.Sdk.Support.V1.Topics;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Rixl.Sdk.Support.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \support\v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The categories property</summary>
        public global::Rixl.Sdk.Support.V1.Categories.CategoriesRequestBuilder Categories
        {
            get => new global::Rixl.Sdk.Support.V1.Categories.CategoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The chat property</summary>
        public global::Rixl.Sdk.Support.V1.Chat.ChatRequestBuilder Chat
        {
            get => new global::Rixl.Sdk.Support.V1.Chat.ChatRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tickets property</summary>
        public global::Rixl.Sdk.Support.V1.Tickets.TicketsRequestBuilder Tickets
        {
            get => new global::Rixl.Sdk.Support.V1.Tickets.TicketsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The topics property</summary>
        public global::Rixl.Sdk.Support.V1.Topics.TopicsRequestBuilder Topics
        {
            get => new global::Rixl.Sdk.Support.V1.Topics.TopicsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Support.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/support/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Rixl.Sdk.Support.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/support/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
